repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint  # Use pylint from Poetry-managed environment
        language: system
        types: [python]

