name: Code Analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          make install

      - name: Run Pylint
        run: |
          make lint

      - name: Run Bandit (Security Analysis)
        run: |
          pip install bandit
          bandit -r web_scraper/

      - name: Check for Secrets in Commits
        uses: dawidd6/action-automatic-releases@v0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: "git log -1 --pretty=%B | grep -i 'password\|secret\|token'"
