name: Code Analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # You can specify a single version since it's for analysis

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-analysis-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-analysis-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-dev  # Optionally skip dev dependencies if not needed

      - name: Run Pylint
        run: |
          make lint

      - name: Run Bandit for Security Analysis
        run: |
          pip install bandit
          bandit -r web_scraper/ -f json -o bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Scan for Secrets in Commits
        uses: zricethezav/gitleaks-action@v2.3.0
        with:
          args: "--path=./ --verbose"
